package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetStationsHandlerFunc turns a function with the right signature into a get stations handler
type GetStationsHandlerFunc func(GetStationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStationsHandlerFunc) Handle(params GetStationsParams) middleware.Responder {
	return fn(params)
}

// GetStationsHandler interface for that can handle valid get stations params
type GetStationsHandler interface {
	Handle(GetStationsParams) middleware.Responder
}

// NewGetStations creates a new http.Handler for the get stations operation
func NewGetStations(ctx *middleware.Context, handler GetStationsHandler) *GetStations {
	return &GetStations{Context: ctx, Handler: handler}
}

/*GetStations swagger:route GET /stations getStations

List of stations

List of all the stations TODO
Supports pagination


*/
type GetStations struct {
	Context *middleware.Context
	Handler GetStationsHandler
}

func (o *GetStations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetStationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
