package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NikolayGenov/sofiatraffic-api/models"
)

/*GetLinesOK An array of stations

swagger:response getLinesOK
*/
type GetLinesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Station `json:"body,omitempty"`
}

// NewGetLinesOK creates GetLinesOK with default headers values
func NewGetLinesOK() *GetLinesOK {
	return &GetLinesOK{}
}

// WithPayload adds the payload to the get lines o k response
func (o *GetLinesOK) WithPayload(payload []*models.Station) *GetLinesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get lines o k response
func (o *GetLinesOK) SetPayload(payload []*models.Station) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Station, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
