package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetStationsParams creates a new GetStationsParams object
// with the default values initialized.
func NewGetStationsParams() GetStationsParams {
	var ()
	return GetStationsParams{}
}

// GetStationsParams contains all the bound params for the get stations operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetStations
type GetStationsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetStationsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
