package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/NikolayGenov/sofiatraffic-api/models"
)

// NewPostLinesParams creates a new PostLinesParams object
// with the default values initialized.
func NewPostLinesParams() PostLinesParams {
	var ()
	return PostLinesParams{}
}

// PostLinesParams contains all the bound params for the post lines operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostLines
type PostLinesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The line to create.
	  Required: true
	  In: body
	*/
	Line *models.Line
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostLinesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Line
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("line", "body"))
			} else {
				res = append(res, errors.NewParseError("line", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Line = &body
			}
		}

	} else {
		res = append(res, errors.Required("line", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
